apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
      - name: node-app
        image: mickta/node-app:v1   # Ton image Docker Hub
        ports:
        - containerPort: 3000
        env:
        # Host et port du service PostgreSQL
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"

        # Nom de la base depuis ton ConfigMap
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB

        # Utilisateur & mot de passe depuis ton Secret PostgreSQL
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node-app
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30080

